services:
  db:
    container_name: postgres-spring-boot
    image: postgres:latest
    environment:
      POSTGRES_USER: bibek
      POSTGRES_PASSWORD: password
      POSTGRES_DB: software_engineer
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5342:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
